Shredder.delete_all
Trail.delete_all
Ride.delete_all

shredder1 = Shredder.create(name: "Mike", skill: 6)
shredder2 = Shredder.create(name: "Jerry", skill: 2) 
shredder3 = Shredder.create(name: "Jill", skill: 8)
shredder4 = Shredder.create(name: "Dustin", skill: 9)
shredder5 = Shredder.create(name: "Jake", skill: 1)
shredder6 = Shredder.create(name: "Yuki", skill: 8) 
shredder7 = Shredder.create(name: "Crystal", skill: 7) 
shredder8 = Shredder.create(name: "Jared", skill: 3) 
shredder9 = Shredder.create(name: "Drew", skill: 6) 
shredder10 = Shredder.create(name: "Amanda", skill: 3)  

# make sure to make trails ids match their difficulty in ascending order
trail1 = Trail.create(name: "Training Wheels", difficulty: 1)
trail2 = Trail.create(name: "Bottoms Up", difficulty: 2)
trail3 = Trail.create(name: "Cruise Control", difficulty: 3)
trail4 = Trail.create(name: "Steeper Sweeper", difficulty: 4)
trail5 = Trail.create(name: "Snowdance", difficulty: 5)
trail6 = Trail.create(name: "Slipperdoodle", difficulty: 6) 
trail7 = Trail.create(name: "Misty", difficulty: 7) 
trail8 = Trail.create(name: "Viewpoint", difficulty: 8) 
trail9 = Trail.create(name: "ProOrNo", difficulty: 9) 
trail10 = Trail.create(name: "Kamikaze", difficulty: 10) 

ride1 = Ride.create(shredder: shredder1, trail: trail1, time: 72)
ride2 = Ride.create(shredder: shredder2, trail: trail2, time: 88)
ride3 = Ride.create(shredder: shredder3, trail: trail3, time: 76)
ride4 = Ride.create(shredder: shredder2, trail: trail3, time: 56)
ride5 = Ride.create(shredder: shredder4, trail: trail2, time: 67)
ride6 = Ride.create(shredder: shredder8, trail: trail2, time: 43)
ride7 = Ride.create(shredder: shredder5, trail: trail1, time: 76)
ride8 = Ride.create(shredder: shredder10, trail: trail2, time: 37)
ride9 = Ride.create(shredder: shredder9, trail: trail1, time: 46)
ride10 = Ride.create(shredder: shredder6, trail: trail4, time: 78)
ride11 = Ride.create(shredder: shredder3, trail: trail5, time: 42)
ride12 = Ride.create(shredder: shredder6, trail: trail6, time: 45)
ride13 = Ride.create(shredder: shredder8, trail: trail4, time: 69)
ride14 = Ride.create(shredder: shredder7, trail: trail7, time: 72)
ride15 = Ride.create(shredder: shredder9, trail: trail5, time: 81)
ride16 = Ride.create(shredder: shredder3, trail: trail4, time: 88)
ride17 = Ride.create(shredder: shredder7, trail: trail6, time: 57)
ride18 = Ride.create(shredder: shredder5, trail: trail8, time: 65)
ride19 = Ride.create(shredder: shredder10, trail: trail7, time: 61)
ride20 = Ride.create(shredder: shredder9, trail: trail9, time: 58)
ride21 = Ride.create(shredder: shredder6, trail: trail10, time: 91)